### ISSUE TITLE
[Feature Request] Add custom sample sounds e.g Flute

### ISSUE THREAD

**Issue by Derpitron** [Studio-kalavati/bandish-editor#104]
I want to practice with flute sounds instead lf santoor. Is it possible to "drop in" custom soundfonts/samples?

**Comment by shark8me** [comment]
It is possible, but may not sound right without additional work.

Samples from instruments like flute and harmonium have a continuous tone
(unlike Santoor and guitar) and therefore need to be looped to play
multiple notes. The app doesn't looped note playback at this point.
