### ISSUE TITLE
Log In Not possible

### ISSUE THREAD

**Issue by cFlour** [Studio-kalavati/bandish-editor#120]
Since swaranotebook has moved to a new web address, everytime I click on the Log In button it redirects to the swaranotebook link, hence not allowing to log in. Please fix it.

**Comment by shark8me** [comment]
Hi,

Please use [this URL](https://bandish-editor.web.app/) in the interim, you might need to log in twice. To fix [this issue](https://github.com/Studio-kalavati/bandish-editor/issues/116), I'd had to change hosting providers, and the DNS will take a couple of days to settle down before swaranotebook.com points to the new URL.
