### ISSUE TITLE
Add support for Bangla fonts

### ISSUE THREAD

**Issue by shark8me** [Studio-kalavati/bandish-editor#72]

**Comment by RajarshiRit** [comment]
issue: Graphical display needs spelling correction. 
Present form: সা রে গা মা পা ধা নি  
Corrected form (As per Bhatkhande system): সা রে গ ম প ধ নি

**Comment by shark8me** [comment]
Thanks for the comment. 
Number of images to be fixed: g, m, p, d x 2 (including komal) x 3 (3 octaves) , totally 24 images.

**Comment by RajarshiRit** [comment]
Px1 . P dont have Komal and Tivra variations.

**Comment by RajarshiRit** [comment]
basically P× 1 × 3 Because P doesnt have a komal and tivra variation.

**Comment by RajarshiRit** [comment]
Please find the ZIP file, containing images of Bengali fonts.

**Comment by RajarshiRit** [comment]
[BENGALI_IMPROVED.zip](https://github.com/Studio-kalavati/bandish-editor/files/10709882/BENGALI_IMPROVED.zip)

**Comment by shark8me** [comment]
Resolved hence closing
