### ISSUE TITLE
Raga notes are not saved

### ISSUE THREAD

**Issue by shark8me** [Studio-kalavati/bandish-editor#84]
Change the default notes in a raga (e.g add komal svaras).
Click on 'raga' again, the previous selected notes are not selected.

**Comment by RajarshiRit** [comment]
There are several other scopes to improvement I shall discuss after I
return from the tour. The errors are as follows:

1. After entering lyrics, when leaving the text keyboard leaves a
whitespace, about half of the screen, persists.

2. Noise while play, especially while editing for long time.

**Comment by shark8me** [comment]
Thanks,
Could you share a screenshot of the first issue?

On the second, do you know when it happens? All the time or when you do
something specific?

**Comment by RajarshiRit** [comment]
I will send it in one week or two. Currently busy with a tour.

**Comment by ameya-deshmukh** [comment]
@shark8me love the project being having trained in Indian classical music myself! I've been exploring Clojure and wanted to start contributing, this seems like the perfect fit. Can I take this (or any other important issue) up?

**Comment by shark8me** [comment]
@ameya-deshmukh sounds good!
Its worth taking a look, however this is a slightly complex issue. If you are familiar with Clojurescript + re-frame, it should be easier. 
I'll create a separate list (or set of labels) for issues that are appropriate for contributors new to the project

**Comment by shark8me** [comment]
This issue is a duplicate of #96 and is now fixed
